Invoice validation #87
MilosPaunovic/invoicr pull request #93
Opened 2021-11-04 21:07 UTC by Aleksalje

Invoice validation #87

2021-11-05 09:32 UTC, MilosPaunovic requested changes
Nice direction, @Aleksalje!

I just think its better, performance wise, to wrap inputs in a`QForm` component than to create separate computed properties for every field.

That way you could revert rules to be field specific, you could leave the `Add` button always enabled but inside a method that handles adding or editing, to validate form first, and in case of an error, mark invalid fields and focus the first errored input from the top.

2021-11-05 09:32 UTC, MilosPaunovic commented on src/components/invoices/Dialog.vue
> +              (val) => isValidAmount || 'Amount is must be bigger than zero',
Check copy for error message.

2021-11-05 09:32 UTC, MilosPaunovic commented on src/components/invoices/Dialog.vue
> +              (val) => isValidExchange || 'Amount is must be bigger than zero',
Check copy for error message.

2021-11-05 09:34 UTC, MilosPaunovic commented
@Aleksalje @jelenamilanovic 

Take a look at this [document](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) when you find the time, specifically, the PR keywords which will help us automate closing issues.

2021-11-12 20:14 UTC, Aleksalje commented on src/components/invoices/Dialog.vue
> +              (val) => isValidAmount || 'Amount is must be bigger than zero',
Copy corrected

2021-11-12 20:15 UTC, Aleksalje commented on src/components/invoices/Dialog.vue
> +              (val) => isValidExchange || 'Amount is must be bigger than zero',
Copy corrected

2021-11-12 20:19 UTC, Aleksalje commented
Reverted computed rules for fields. 
The issue was that the button was emitting an event to close the popup.
Removed close-popup event and changed the button type to submit.

2021-11-12 20:20 UTC, merged